# Generated by Django 5.0.6 on 2025-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_remove_sequencingdocument_created_by_approvalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
