# Generated by Django 5.0.6 on 2025-08-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalrequest_comments'),
        ('metadata', '0004_project_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='expriments',
            field=models.ManyToManyField(blank=True, null=True, related_name='approval_requests', to='metadata.experiment'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approval_requests', to='metadata.project'),
        ),
    ]
