# Generated by Django 5.0.6 on 2025-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvalrequest_expriments_approvalrequest_project'),
        ('metadata', '0004_project_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='expriments',
            field=models.ManyToManyField(related_name='approval_requests', to='metadata.experiment'),
        ),
    ]
