# Generated by Django 5.0.6 on 2025-08-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approvalrequest_expriments'),
        ('metadata', '0004_project_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approval_requests', to='metadata.project'),
        ),
    ]
