# Generated by Django 5.0.6 on 2025-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_rename_expriments_approvalrequest_experiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('completed', 'Completed')], default='pending', max_length=11),
        ),
    ]
