# Generated by Django 5.0.6 on 2024-06-18 17:25

import django.db.models.deletion
import metadata.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='json_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='json_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='json_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimenttag',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experimenttag',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='jsonobj',
            name='json_fields',
            field=models.JSONField(default=metadata.models.JsonObj.fields_default),
        ),
        migrations.AlterField(
            model_name='modification',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modification',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='edited_by',
            field=models.ForeignKey(help_text='Who edited this object last', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='json_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
