# Generated by Django 5.0.6 on 2025-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('metadata', '0003_alter_biosample_id_alter_biosource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='lab.lab'),
        ),
    ]
