version: '3'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ims_db
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
      - ../db-initialization:/docker-entrypoint-initdb.d
      - ../../db_backups:/db_backups
  web:
    restart: always
    build: .
    environment:
       - DEVELOPMENT=1
    env_file:
       - ./config/db_variables.env
    command: bash /code/start_django_server.sh
    volumes:
      - ../ims:/ims
      - ../../media:/ims/media
    ports:
      - "8000:8000"
    depends_on:
      - db