# Use a minimal base image
FROM python:3.12-slim AS base

# Prevent Python from writing pyc files and enable unbuffered output
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  POETRY_VIRTUALENVS_CREATE=false

# Install system dependencies
RUN apt-get update -y && \
  apt-get install -y --no-install-recommends \
  build-essential graphviz graphviz-dev netcat-openbsd libpq-dev && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a working directory
WORKDIR /code

# Copy requirements file and install Python dependencies
COPY ./config/pip-requirements.txt /code/
RUN pip install --no-cache-dir --upgrade pip && \
  pip install --no-cache-dir -r pip-requirements.txt

# Copy the start script and make it executable
COPY start_django_server.sh /code/
RUN chmod +x /code/start_django_server.sh

# Set the working directory for the Django application
WORKDIR /ims
