services:
  db:
    image: postgres:12.2
    container_name: ims_db
    restart: always
    env_file:
       - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
      - ../db-initialization:/docker-entrypoint-initdb.d
      - ../../db_backups:/db_backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: ims_web
    restart: always
    env_file:
      - .env
    environment:
      PRODUCTION: 1
    command: ["bash", "/code/start_django_server.sh"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../ims:/ims
      - ../../static:/ims/static
      - ../../media:/ims/media
    ports:
      - "5050:5050"

  nginx:
    image: nginx:1.25-alpine
    container_name: ims_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../static:/static
      - ../ims:/src
      - ./config/nginx:/etc/nginx/conf.d
