version: '3'

services:
  db:
    image: postgres:12.2
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
      - ../db-initialization:/docker-entrypoint-initdb.d
      - ../../db_backups:/db_backups
  web:
    restart: always
    build: .
    environment:
       - PRODUCTION=1
    env_file:
       - .env.production
    command: bash /code/start_django_server.sh
    volumes:
      - ../ims:/ims
      - ../../static:/ims/static
      - ../../media:/ims/media
    ports:
      - "5050:5050"
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../static:/static
      - ../ims:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
